name: docker

on:
    workflow_dispatch:
    push:
        branches: [ main ]

jobs:
    fundoc:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            -   name: Log in to the GitHub Container registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker images
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ghcr.io/thisismana/fundoc:latest
